# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dbc226b6f61362cb766947b539cd3d21adbf8117b462d48d6ce5355568917c5b451ee2bad9e5ecf37e704916ca2d8023acb714dc354cd6a9c90109ce7b391e32

test:
  secret_key_base: e937c42fd0b94305b55de79e6f265f22db29d61237d4de2d65475a8fbe55c016e6e8423262c4deb610df3d998515aaf59712f7ac65cd0806a3fe5552a990d7e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
